### ISSUE TITLE
About paper results

### ISSUE THREAD

**Issue by hltechl** [ghuan99/CCDistill#3]
I am very inspired by your paper.
I know that the recently released benchmarks on the test set of the ACDC dataset are very active.
Are there any confirmed scores on ACDC nighttime test dataset?
[ACDC dataset] (https://acdc.vision.ee.ethz.ch/benchmarks#semanticSegmentation)

I'm also curious about your implementation. When will the code be released?

**Comment by ghuan99** [comment]
Thank you so much for your interest in our work!  
I just submitted the prediction of ACDC-test dataset on this website. And got the following result (mIoU: 49):
![图片](https://user-images.githubusercontent.com/101086744/187392105-76dd8042-a6a7-47b9-8486-94f0bbae23d2.png)
We will submit it to the benchmark soon. Also the code will be released after some time.

**Comment by hltechl** [comment]
Thanks for replying!
